#!/bin/bash

# Create symbolic links from config files
PWD=`pwd`
rm -f ~/.bashrc ~/.screenrc ~/.ps1 ~/.gitconfig ~/.emacs
ln -s $PWD/bashrc ~/.bashrc
ln -s $PWD/screenrc ~/.screenrc
ln -s $PWD/ps1 ~/.ps1
ln -s $PWD/gitconfig ~/.gitconfig
ln -s $PWD/emacs ~/.emacs
ln -s $PWD/vimrc ~/.vimrc

# Create emacs plugins directory
mkdir -p ~/.emacs.d/scripts

emacs_plugin ()
{
    mode_name=$1.el
    mode_web_addr=$2
    wget -O ~/.emacs.d/scripts/$mode_name $mode_web_addr
}

# Get the plugins
emacs_plugin markdown-mode http://jblevins.org/projects/markdown-mode/markdown-mode.el
emacs_plugin go-mode       http://golang.org/misc/emacs/go-mode.el?m=text

# Emacs speaks statistics
rm -rf ~/.emacs.d/scripts/ess
git clone https://github.com/emacs-ess/ESS.git ~/.emacs.d/scripts/ess
