#!/bin/bash

create()
{
    root_dir=$1
    shift

    backup_dir=$root_dir/backups/`date +%Y-%m-%d-%H-%M-%S`
    mkdir -p $backup_dir

    for cfg in $@
    do
        cp ~/.$cfg $backup_dir/$cfg 2>/dev/null
        rm -f ~/.$cfg
        mkdir -p $(dirname ~/.$cfg)
        ln -s $root_dir/$cfg ~/.$cfg
    done
}

# use this instead of readlink to make it not dependent on linux
root_dir=`echo $(cd $(dirname "$1") && pwd -P)/$(basename "$1")`
# Create symbolic links from config files
create $root_dir bashrc screenrc ps1 gitconfig i3/config emacs.d/init.el
